@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Клиент такси-сервиса\nв ЮВА или Южной Америке")
Component(public_dns, "Public DNS Resolver", "ISP/Local DNS", "Первоначальное разрешение DNS")
Component(cdn_resolver, "GeoDNS Router\nRoute53/Cloudflare", "Latency-Based Routing", "Определение ближайшего региона\nпо задержке и здоровью")


System_Boundary(sea_region, "Юго-Восточная Азия") {
    Component(sea_alb, "Singapore Application load balancer")
    Container(sea_app, "Singapore Application Servers")
    Rel(sea_alb, sea_app, "Направляет запросы к")

}

System_Boundary(main_region, "Главный Регион компании FutureGO") {
    Component(main_lb, "Main Application load balancer")
    Container(main_servers, "Main Application Servers")
    Rel(main_lb, main_servers, "Направляет запросы к")
}

System_Boundary(sa_region,  "Южная Америка") {
    Component(sa_alb, "Buenos-Aires Application load balancer")
    Container(sa_app, "Buenos-Aires Application Servers")
    Rel(sa_alb, sa_app, "Направляет запросы к")
}

Rel(user, public_dns, "DNS запрос", "UDP")
Rel(public_dns, cdn_resolver, "DNS разрешение", "UDP")

Rel(cdn_resolver, sea_alb, "Пользователи ЮВА", "HTTPS")
Rel(cdn_resolver, sa_alb, "Пользователи ЮА", "HTTPS")
Rel(cdn_resolver, main_lb, "Пользователи Главного сервера", "HTTPS")

@enduml